trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - '*'

variables:
  - name: app_version
    value: test

jobs:
- job: build_and_test
  pool:
    vmImage: ubuntu-20.04
  strategy:
    maxParallel: 1
    matrix:
      python35:
        python.version: '3.5'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'
  - script: pip install -r requirements.txt
    displayName: 'Install pip packages'
  - script: ./release.sh test 7.1.1 $(app_version) 
    displayName: 'Build Docker image with Android 7.1.1 and run unit tests'
  - script: bash <(curl -s https://codecov.io/bash)
    displayName: 'Publish test result'
